ldns: update to 1.8.4
Disable Python bindings due to incompatibility with newer SWIG:

.../ldns-1.8.4/contrib/python/ldns_wrapper.c:8421:15: error: too few arguments to function 'SWIG_Python_AppendOutput'
  8421 |   resultobj = SWIG_Python_AppendOutput(resultobj,
       |               ^~~~~~~~~~~~~~~~~~~~~~~~